In [1]:
import pandas as pd

In [ ]:
from pathlib import Path

# Get project root directory dynamically
project_root = Path.cwd()
if not (project_root / 'data').exists():
    project_root = project_root.parent

raw_data_path = project_root / 'data' / 'raw'
processed_data_path = project_root / 'data' / 'processed'
processed_data_path.mkdir(parents=True, exist_ok=True)

In [ ]:
df_1 = pd.read_csv(raw_data_path / '01_fund_master.csv')
df_2 = pd.read_csv(raw_data_path / '02_nav_history.csv')
df_3 = pd.read_csv(raw_data_path / '03_aum_by_fund_house.csv')
df_4 = pd.read_csv(raw_data_path / '04_monthly_sip_inflows.csv')
df_5 = pd.read_csv(raw_data_path / '05_category_inflows.csv')
df_6 = pd.read_csv(raw_data_path / '06_industry_folio_count.csv')
df_7 = pd.read_csv(raw_data_path / '07_scheme_performance.csv')
df_8 = pd.read_csv(raw_data_path / '08_investor_transactions.csv')
df_9 = pd.read_csv(raw_data_path / '09_portfolio_holdings.csv')
df_10 = pd.read_csv(raw_data_path / '10_benchmark_indices.csv')

print(f"✓ Loaded data from: {raw_data_path}")

In [4]:
df_1

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02
5,100016,HDFC Mutual Fund,HDFC Top 100 Fund - Regular Plan - Growth,Equity,Large Cap,Regular,1996-09-11,NIFTY 100 TRI,1.55,1.0,500,1000,Rahul Baijal,Moderate,EC01
6,125497,HDFC Mutual Fund,HDFC Top 100 Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.92,1.0,500,1000,Rahul Baijal,Moderate,EC01
7,100033,HDFC Mutual Fund,HDFC Mid-Cap Opportunities Fund - Regular - Gr...,Equity,Mid Cap,Regular,2007-06-25,NIFTY Midcap 150 TRI,1.38,1.0,500,1000,Chirag Setalvad,High,EC02
8,125498,HDFC Mutual Fund,HDFC Mid-Cap Opportunities Fund - Direct - Growth,Equity,Mid Cap,Direct,2013-01-01,NIFTY Midcap 150 TRI,0.78,1.0,500,1000,Chirag Setalvad,High,EC02
9,100025,HDFC Mutual Fund,HDFC Short Term Debt Fund - Regular - Growth,Debt,Short Duration,Regular,2002-06-25,CRISIL Short Term Bond Index,0.56,0.5,500,1000,Anil Bamboli,Low,DC02
10,120503,ICICI Prudential MF,ICICI Pru Bluechip Fund - Regular - Growth,Equity,Large Cap,Regular,2008-05-23,NIFTY 100 TRI,1.42,1.0,500,1000,Anish Tawakley,Moderate,EC01
11,120504,ICICI Prudential MF,ICICI Pru Bluechip Fund - Direct - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.80,1.0,500,1000,Anish Tawakley,Moderate,EC01
12,120505,ICICI Prudential MF,ICICI Pru Midcap Fund - Regular - Growth,Equity,Mid Cap,Regular,2004-10-28,NIFTY Midcap 150 TRI,1.36,1.0,500,1000,Sankaran Naren,High,EC02
13,120506,ICICI Prudential MF,ICICI Pru Value Discovery Fund - Regular - Growth,Equity,Value,Regular,2004-08-16,NIFTY 500 TRI,1.41,1.0,500,1000,Sankaran Naren,Moderately High,EC06
14,120507,ICICI Prudential MF,ICICI Pru Liquid Fund - Regular - Growth,Debt,Liquid,Regular,2001-11-17,CRISIL Liquid Fund AI Index,0.74,0.0,500,5000,Rahul Goswami,Low,DC01
15,118632,Nippon India MF,Nippon India Large Cap Fund - Regular - Growth,Equity,Large Cap,Regular,2004-08-08,NIFTY 100 TRI,1.51,1.0,500,1000,Sailesh Raj Bhan,Moderate,EC01
16,118633,Nippon India MF,Nippon India Large Cap Fund - Direct - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.72,1.0,500,1000,Sailesh Raj Bhan,Moderate,EC01
17,118634,Nippon India MF,Nippon India Small Cap Fund - Regular - Growth,Equity,Small Cap,Regular,2010-09-16,BSE 250 SmallCap TRI,1.53,1.0,500,1000,Samir Rachh,Very High,EC03
18,118635,Nippon India MF,Nippon India ETF Nifty 50 BeES,Equity,Index/ETF,Direct,2001-12-28,NIFTY 50 TRI,0.89,0.0,500,100,Vishal Jain,Moderate,EI01
19,118636,Nippon India MF,Nippon India Gilt Securities Fund - Regular - ...,Debt,Gilt,Regular,1999-08-19,CRISIL Dynamic Gilt Index,0.55,0.0,500,1000,Vivek Sharma,Low,DC02
20,120841,Kotak Mahindra MF,Kotak Bluechip Fund - Regular - Growth,Equity,Large Cap,Regular,2005-12-29,NIFTY 100 TRI,1.59,1.0,500,1000,Harsha Upadhyaya,Moderate,EC01
21,120842,Kotak Mahindra MF,Kotak Emerging Equity Fund - Regular - Growth,Equity,Mid Cap,Regular,2007-03-30,NIFTY Midcap 150 TRI,1.56,1.0,500,1000,Pankaj Tibrewal,High,EC02
22,120843,Kotak Mahindra MF,Kotak Flexicap Fund - Regular - Growth,Equity,Flexi Cap,Regular,2009-08-11,NIFTY 500 TRI,1.45,1.0,500,1000,Pankaj Tibrewal,Moderately High,EC04
23,120844,Kotak Mahindra MF,Kotak Liquid Fund - Regular - Growth,Debt,Liquid,Regular,2004-03-03,CRISIL Liquid Fund AI Index,0.60,0.0,500,5000,Deepak Agrawal,Low,DC01
24,119092,Axis Mutual Fund,Axis Bluechip Fund - Regular - Growth,Equity,Large Cap,Regular,2010-01-05,NIFTY 100 TRI,1.64,1.0,500,1000,Shreyash Devalkar,Moderate,EC01
25,119093,Axis Mutual Fund,Axis Bluechip Fund - Direct - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.75,1.0,500,1000,Shreyash Devalkar,Moderate,EC01
26,119094,Axis Mutual Fund,Axis Midcap Fund - Regular - Growth,Equity,Mid Cap,Regular,2011-02-18,NIFTY Midcap 50 TRI,1.38,1.0,500,1000,Jinesh Gopani,High,EC02
27,119095,Axis Mutual Fund,Axis Small Cap Fund - Regular - Growth,Equity,Small Cap,Regular,2013-11-29,BSE 250 SmallCap TRI,1.38,1.0,500,1000,Anupam Tiwari,Very High,EC03
28,101206,Aditya Birla Sun Life MF,ABSL Frontline Equity Fund - Regular - Growth,Equity,Large Cap,Regular,2002-08-30,NIFTY 100 TRI,1.60,1.0,500,1000,Mahesh Patil,Moderate,EC01
29,101207,Aditya Birla Sun Life MF,ABSL Small Cap Fund - Regular - Growth,Equity,Small Cap,Regular,2007-05-31,BSE 250 SmallCap TRI,1.53,1.0,500,1000,Mircea Ciobanu,Very High,EC03
30,101208,Aditya Birla Sun Life MF,ABSL Liquid Fund - Regular - Growth,Debt,Liquid,Regular,2000-04-17,CRISIL Liquid Fund AI Index,0.79,0.0,500,5000,Maneesh Dangi,Low,DC01
31,102885,UTI Mutual Fund,UTI Nifty 50 Index Fund - Regular - Growth,Equity,Index,Regular,2000-03-06,NIFTY 50 TRI,1.57,0.0,500,1000,Sharwan Kumar Goyal,Moderate,EI01
32,102886,UTI Mutual Fund,UTI Mid Cap Fund - Regular - Growth,Equity,Mid Cap,Regular,2004-04-07,NIFTY Midcap 150 TRI,1.51,1.0,500,1000,V Srivatsa,High,EC02
33,102887,UTI Mutual Fund,UTI Flexi Cap Fund - Regular - Growth,Equity,Flexi Cap,Regular,2005-05-18,NIFTY 500 TRI,1.64,1.0,500,1000,Ajay Tyagi,Moderately High,EC04
34,148567,Mirae Asset MF,Mirae Asset Large Cap Fund - Regular - Growth,Equity,Large Cap,Regular,2008-04-04,NIFTY 100 TRI,1.46,1.0,500,1000,Gaurav Misra,Moderate,EC01
35,148568,Mirae Asset MF,Mirae Asset Emerging Bluechip Fund - Regular -...,Equity,Large & Mid Cap,Regular,2010-07-09,NIFTY Large Midcap 250 TRI,1.52,1.0,500,1000,Neelesh Surana,Moderately High,EC04
36,148569,Mirae Asset MF,Mirae Asset Tax Saver Fund - Regular - Growth,Equity,ELSS,Regular,2015-12-28,NIFTY 500 TRI,1.60,1.0,500,1000,Neelesh Surana,High,EC05
37,149322,DSP Mutual Fund,DSP Top 100 Equity Fund - Regular - Growth,Equity,Large Cap,Regular,2003-03-10,NIFTY 100 TRI,1.54,1.0,500,1000,Apoorva Shah,Moderate,EC01
38,149323,DSP Mutual Fund,DSP Midcap Fund - Regular - Growth,Equity,Mid Cap,Regular,2006-11-16,NIFTY Midcap 150 TRI,1.61,1.0,500,1000,Vinit Sambre,High,EC02
39,149324,DSP Mutual Fund,DSP Small Cap Fund - Regular - Growth,Equity,Small Cap,Regular,2007-06-14,BSE 250 SmallCap TRI,1.52,1.0,500,1000,Vinit Sambre,Very High,EC03

In [5]:
df_2['date'] = pd.to_datetime(df_2['date'], format='%Y-%m-%d')

In [6]:
df_2.sort_values(by=['date','amfi_code'], inplace=True)

In [7]:
df_2

       amfi_code       date       nav
5750      100016 2022-01-03  520.4608
10350     100025 2022-01-03   26.3169
8050      100033 2022-01-03  107.3758
32200     101206 2022-01-03  305.0996
33350     101207 2022-01-03   38.5736
...          ...        ...       ...
41399     148568 2026-05-29  205.4510
42549     148569 2026-05-29   97.7435
43699     149322 2026-05-29  606.2349
44849     149323 2026-05-29  245.3651
45999     149324 2026-05-29  279.7511

[46000 rows x 3 columns]

In [8]:
df_2[df_2['nav'] <0]
df_2[df_2['nav'] == 0]

Empty DataFrame
Columns: [amfi_code, date, nav]
Index: []

In [9]:
df_2.duplicated().sum()

0

In [10]:
new_type=pd.get_dummies(df_8['transaction_type'], prefix='transaction_type')

In [11]:
df_8.drop(['transaction_type'], axis=1, inplace=True)

In [12]:
df_8=df_8.join(new_type)

In [13]:
df_8

,investor_id,transaction_date,amfi_code,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status,transaction_type_Lumpsum,transaction_type_Redemption,transaction_type_SIP
0,INV003054,2024-01-01,119092,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified,False,False,True
1,INV002952,2024-01-01,148567,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified,False,True,False
2,INV003420,2024-01-01,118636,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified,False,False,True
3,INV003436,2024-01-01,118634,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending,False,False,True
4,INV004691,2024-01-01,119094,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32773,INV003340,2025-05-30,101207,168029,Madhya Pradesh,Indore,T30,26-35,Male,22.5,Net Banking,Verified,True,False,False
32774,INV001838,2025-05-30,119093,2175,Uttar Pradesh,Kanpur,B30,46-55,Male,27.6,Mandate,Verified,False,False,True
32775,INV000074,2025-05-30,120504,25998,Rajasthan,Jaipur,T30,26-35,Female,8.4,UPI,Verified,False,False,True
32776,INV002929,2025-05-30,148568,459,West Bengal,Kolkata,T30,26-35,Male,13.0,Mandate,Verified,False,False,True
32777,INV001852,2025-05-30,118633,226721,Telangana,Hyderabad,T30,26-35,Male,21.7,Cheque,Verified,False,True,False

In [14]:
df_8[df_8['amount_inr']<0]
df_8[df_8['amount_inr']==0]

Empty DataFrame
Columns: [investor_id, transaction_date, amfi_code, amount_inr, state, city, city_tier, age_group, gender, annual_income_lakh, payment_mode, kyc_status, transaction_type_Lumpsum, transaction_type_Redemption, transaction_type_SIP]
Index: []

In [15]:
df_8['transaction_date'] = pd.to_datetime(df_8['transaction_date'], format='%Y-%m-%d')

In [16]:
df_8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   investor_id                  32778 non-null  object
 1   transaction_date             32778 non-null  datetime64[ns]
 2   amfi_code                    32778 non-null  int64
 3   amount_inr                   32778 non-null  int64
 4   state                        32778 non-null  object
 5   city                         32778 non-null  object
 6   city_tier                    32778 non-null  object
 7   age_group                    32778 non-null  object
 8   gender                       32778 non-null  object
 9   annual_income_lakh           32778 non-null  float64
 10  payment_mode                 32778 non-null  object
 11  kyc_status                   32778 non-null  object
 12  transaction_type_Lumpsum     32778 non-null  bool
 13  transaction_type_Redemption  32778 non-null  bool
 14  transaction_type_SIP         32778 non-null  bool
dtypes: bool(3), datetime64[ns](1), float64(1), int64(2), object(8)
memory usage: 3.1+ MB

In [17]:
df_8['kyc_status'].unique()

array(['Verified', 'Pending'], dtype=object)

In [18]:
df_8.sort_values(by=['transaction_date','amfi_code'], inplace=True)

In [19]:
df_7

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low
5,100016,HDFC Top 100 Fund - Regular Plan - Growth,HDFC Mutual Fund,Large Cap,Regular,10.94,14.84,11.32,14.06,0.78,0.97,1.06,1.70,14.0,-17.41,6434,1.55,5,Moderate
6,125497,HDFC Top 100 Fund - Direct Plan - Growth,HDFC Mutual Fund,Large Cap,Direct,11.48,13.38,13.48,12.25,1.13,0.97,0.96,1.45,14.0,-33.50,10611,0.92,4,Moderate
7,100033,HDFC Mid-Cap Opportunities Fund - Regular - Gr...,HDFC Mutual Fund,Mid Cap,Regular,15.43,16.58,17.69,15.63,0.95,0.91,0.87,1.44,19.0,-13.67,23185,1.38,5,High
8,125498,HDFC Mid-Cap Opportunities Fund - Direct - Growth,HDFC Mutual Fund,Mid Cap,Direct,19.98,15.29,15.85,14.39,0.90,1.04,0.80,1.38,19.0,-32.22,18792,0.78,4,High
9,100025,HDFC Short Term Debt Fund - Regular - Growth,HDFC Mutual Fund,Short Duration,Regular,6.83,7.37,6.41,5.39,1.98,0.44,1.84,2.79,4.0,-6.01,27953,0.56,3,Low
10,120503,ICICI Pru Bluechip Fund - Regular - Growth,ICICI Prudential MF,Large Cap,Regular,15.63,11.54,11.46,10.88,0.66,0.96,0.82,1.12,14.0,-25.91,36022,1.42,4,Moderate
11,120504,ICICI Pru Bluechip Fund - Direct - Growth,ICICI Prudential MF,Large Cap,Direct,14.12,14.41,13.02,13.53,0.88,1.03,1.03,1.27,14.0,-26.59,41553,0.80,3,Moderate
12,120505,ICICI Pru Midcap Fund - Regular - Growth,ICICI Prudential MF,Mid Cap,Regular,14.02,18.08,17.55,17.19,0.89,1.00,0.95,1.45,19.0,-21.84,979,1.36,3,High
13,120506,ICICI Pru Value Discovery Fund - Regular - Growth,ICICI Prudential MF,Value,Regular,16.67,14.76,12.60,14.21,0.55,0.92,0.98,1.50,15.0,-21.89,2571,1.41,4,Moderately High
14,120507,ICICI Pru Liquid Fund - Regular - Growth,ICICI Prudential MF,Liquid,Regular,8.89,7.68,7.94,5.83,1.85,0.26,7.68,10.37,0.5,-2.62,39116,0.74,5,Low
15,118632,Nippon India Large Cap Fund - Regular - Growth,Nippon India MF,Large Cap,Regular,15.84,14.00,14.70,13.14,0.86,0.88,1.00,1.68,14.0,-16.07,20909,1.51,4,Moderate
16,118633,Nippon India Large Cap Fund - Direct - Growth,Nippon India MF,Large Cap,Direct,14.42,12.33,14.72,10.63,1.70,1.02,0.88,1.48,14.0,-18.14,39475,0.72,3,Moderate
17,118634,Nippon India Small Cap Fund - Regular - Growth,Nippon India MF,Small Cap,Regular,21.30,20.15,21.88,19.35,0.80,1.03,0.81,1.14,25.0,-30.87,43630,1.53,4,Very High
18,118635,Nippon India ETF Nifty 50 BeES,Nippon India MF,Index/ETF,Direct,10.14,11.77,12.31,9.97,1.80,1.04,0.91,1.24,13.0,-26.75,20284,0.89,5,Moderate
19,118636,Nippon India Gilt Securities Fund - Regular - ...,Nippon India MF,Gilt,Regular,6.19,5.31,8.71,4.42,0.89,0.37,1.33,2.38,4.0,-2.23,30030,0.55,4,Low
20,120841,Kotak Bluechip Fund - Regular - Growth,Kotak Mahindra MF,Large Cap,Regular,14.37,12.25,13.42,10.98,1.27,0.93,0.87,1.34,14.0,-17.86,35585,1.59,3,Moderate
21,120842,Kotak Emerging Equity Fund - Regular - Growth,Kotak Mahindra MF,Mid Cap,Regular,17.12,18.23,17.75,16.32,1.91,1.00,0.96,1.27,19.0,-21.92,47469,1.56,4,High
22,120843,Kotak Flexicap Fund - Regular - Growth,Kotak Mahindra MF,Flexi Cap,Regular,15.74,15.65,13.50,13.80,1.85,0.95,0.98,1.57,16.0,-19.50,35012,1.45,5,Moderately High
23,120844,Kotak Liquid Fund - Regular - Growth,Kotak Mahindra MF,Liquid,Regular,4.26,6.18,8.26,4.66,1.52,0.47,6.18,9.70,0.5,-3.81,27623,0.60,3,Low
24,119092,Axis Bluechip Fund - Regular - Growth,Axis Mutual Fund,Large Cap,Regular,11.82,11.84,14.14,10.43,1.41,0.91,0.85,1.25,14.0,-27.54,25803,1.64,4,Moderate
25,119093,Axis Bluechip Fund - Direct - Growth,Axis Mutual Fund,Large Cap,Direct,13.95,12.14,13.66,10.71,1.43,0.87,0.87,1.54,14.0,-17.40,15866,0.75,4,Moderate
26,119094,Axis Midcap Fund - Regular - Growth,Axis Mutual Fund,Mid Cap,Regular,14.88,15.18,18.94,13.76,1.42,1.00,0.80,1.18,19.0,-32.38,28996,1.38,5,High
27,119095,Axis Small Cap Fund - Regular - Growth,Axis Mutual Fund,Small Cap,Regular,21.97,20.98,22.62,20.47,0.51,1.00,0.84,1.40,25.0,-14.45,21545,1.38,4,Very High
28,101206,ABSL Frontline Equity Fund - Regular - Growth,Aditya Birla Sun Life MF,Large Cap,Regular,14.82,13.78,12.86,12.44,1.34,1.03,0.98,1.25,14.0,-15.07,23500,1.60,5,Moderate
29,101207,ABSL Small Cap Fund - Regular - Growth,Aditya Birla Sun Life MF,Small Cap,Regular,24.93,22.38,23.80,20.54,1.84,0.97,0.90,1.47,25.0,-23.61,41613,1.53,5,Very High
30,101208,ABSL Liquid Fund - Regular - Growth,Aditya Birla Sun Life MF,Liquid,Regular,6.18,5.14,7.95,3.96,1.18,0.43,5.14,8.76,0.5,-3.66,38995,0.79,5,Low
31,102885,UTI Nifty 50 Index Fund - Regular - Growth,UTI Mutual Fund,Index,Regular,13.76,12.10,11.31,11.17,0.93,0.90,0.93,1.29,13.0,-24.42,7350,1.57,4,Moderate
32,102886,UTI Mid Cap Fund - Regular - Growth,UTI Mutual Fund,Mid Cap,Regular,16.30,15.61,15.86,14.49,1.12,0.92,0.82,1.21,19.0,-13.43,41728,1.51,5,High
33,102887,UTI Flexi Cap Fund - Regular - Growth,UTI Mutual Fund,Flexi Cap,Regular,17.43,15.34,15.78,13.55,1.79,1.00,0.96,1.37,16.0,-12.14,17912,1.64,5,Moderately High
34,148567,Mirae Asset Large Cap Fund - Regular - Growth,Mirae Asset MF,Large Cap,Regular,15.12,14.81,12.68,13.19,1.62,0.96,1.06,1.66,14.0,-17.07,11361,1.46,5,Moderate
35,148568,Mirae Asset Emerging Bluechip Fund - Regular -...,Mirae Asset MF,Large & Mid Cap,Regular,14.91,14.56,15.68,12.86,1.70,0.99,0.91,1.55,16.0,-33.15,49046,1.52,5,Moderately High
36,148569,Mirae Asset Tax Saver Fund - Regular - Growth,Mirae Asset MF,ELSS,Regular,11.16,13.58,14.26,13.04,0.54,0.98,0.80,1.03,17.0,-22.62,2989,1.60,5,High
37,149322,DSP Top 100 Equity Fund - Regular - Growth,DSP Mutual Fund,Large Cap,Regular,11.96,12.82,12.35,11.00,1.82,0.91,0.92,1.63,14.0,-21.70,41828,1.54,5,Moderate
38,149323,DSP Midcap Fund - Regular - Growth,DSP Mutual Fund,Mid Cap,Regular,14.12,17.16,19.00,16.14,1.02,0.98,0.90,1.50,19.0,-26.99,37835,1.61,4,High
39,149324,DSP Small Cap Fund - Regular - Growth,DSP Mutual Fund,Small Cap,Regular,20.20,20.08,20.61,19.39,0.69,0.98,0.80,1.23,25.0,-17.01,35124,1.52,4,Very High

In [20]:
df_7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [21]:
df_7['expense_ratio_pct'].max(),df_7['expense_ratio_pct'].min()

(1.64, 0.55)

In [22]:
df_7['sharpe_ratio'].max(),df_7['sharpe_ratio'].min()

(7.68, 0.8)

In [23]:
df_1['launch_date']= pd.to_datetime(df_1['launch_date'], format='%Y-%m-%d')

In [24]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46000 entries, 5750 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[ns]
 2   nav        46000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 1.4 MB

In [25]:
df_3['date'] = pd.to_datetime(df_3['date'], format='%Y-%m-%d')

In [26]:
df_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     object
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.4+ KB

In [27]:
df_4['yoy_growth_pct'].fillna(0, inplace=True)

C:\Users\JAY MISTRY\AppData\Local\Temp\ipykernel_3180\309821498.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_4['yoy_growth_pct'].fillna(0, inplace=True)

In [28]:
df_5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    object
 1   category          144 non-null    object
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), object(2)
memory usage: 3.5+ KB

In [29]:
df_6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     object
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(5), object(1)
memory usage: 1.1+ KB

In [30]:
df_6

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48
5,2023-04,15.54,10.88,2.18,0.93,1.55
6,2023-07,16.28,11.40,2.28,0.98,1.63
7,2023-10,16.72,11.70,2.34,1.00,1.67
8,2024-01,17.78,12.45,2.49,1.07,1.78
9,2024-04,18.85,13.20,2.64,1.13,1.89
10,2024-07,19.98,13.99,2.80,1.20,2.00
11,2024-10,21.62,15.13,3.03,1.30,2.16
12,2024-12,22.89,16.02,3.20,1.37,2.29
13,2025-01,23.10,16.17,3.23,1.39,2.31
14,2025-03,23.45,16.42,3.28,1.41,2.35
15,2025-04,23.89,16.72,3.34,1.43,2.39
16,2025-07,24.57,17.20,3.44,1.47,2.46
17,2025-08,24.89,17.42,3.48,1.49,2.49
18,2025-09,25.19,17.63,3.53,1.51,2.52
19,2025-10,25.60,17.92,3.58,1.54,2.56
20,2025-12,26.12,18.28,3.66,1.57,2.61

In [31]:
df_9['portfolio_date'] = pd.to_datetime(df_9['portfolio_date'], format='%Y-%m-%d')

In [32]:
df_10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   object
 1   index_name   8050 non-null   object
 2   close_value  8050 non-null   float64
dtypes: float64(1), object(2)
memory usage: 188.8+ KB

In [33]:
df_10['date'] = pd.to_datetime(df_10['date'], format='%Y-%m-%d')

In [34]:
df_1.shape, df_2.shape, df_3.shape, df_4.shape, df_5.shape, df_6.shape, df_7.shape, df_8.shape, df_9.shape, df_10.shape

((40, 15),
 (46000, 3),
 (90, 5),
 (48, 6),
 (144, 3),
 (21, 6),
 (40, 19),
 (32778, 15),
 (322, 8),
 (8050, 3))

In [35]:
df_2

       amfi_code       date       nav
5750      100016 2022-01-03  520.4608
10350     100025 2022-01-03   26.3169
8050      100033 2022-01-03  107.3758
32200     101206 2022-01-03  305.0996
33350     101207 2022-01-03   38.5736
...          ...        ...       ...
41399     148568 2026-05-29  205.4510
42549     148569 2026-05-29   97.7435
43699     149322 2026-05-29  606.2349
44849     149323 2026-05-29  245.3651
45999     149324 2026-05-29  279.7511

[46000 rows x 3 columns]

In [36]:
df_2['daily_return'] = df_2.groupby('amfi_code')['nav'].pct_change()

In [37]:
df_2

       amfi_code       date       nav  daily_return
5750      100016 2022-01-03  520.4608           NaN
10350     100025 2022-01-03   26.3169           NaN
8050      100033 2022-01-03  107.3758           NaN
32200     101206 2022-01-03  305.0996           NaN
33350     101207 2022-01-03   38.5736           NaN
...          ...        ...       ...           ...
41399     148568 2026-05-29  205.4510      0.011354
42549     148569 2026-05-29   97.7435      0.016042
43699     149322 2026-05-29  606.2349      0.002064
44849     149323 2026-05-29  245.3651     -0.002778
45999     149324 2026-05-29  279.7511     -0.003335

[46000 rows x 4 columns]

In [38]:
df_2.fillna(0, inplace=True)

In [39]:
df_2

       amfi_code       date       nav  daily_return
5750      100016 2022-01-03  520.4608      0.000000
10350     100025 2022-01-03   26.3169      0.000000
8050      100033 2022-01-03  107.3758      0.000000
32200     101206 2022-01-03  305.0996      0.000000
33350     101207 2022-01-03   38.5736      0.000000
...          ...        ...       ...           ...
41399     148568 2026-05-29  205.4510      0.011354
42549     148569 2026-05-29   97.7435      0.016042
43699     149322 2026-05-29  606.2349      0.002064
44849     149323 2026-05-29  245.3651     -0.002778
45999     149324 2026-05-29  279.7511     -0.003335

[46000 rows x 4 columns]

In [40]:
df_2[df_2['amfi_code']==100016]

      amfi_code       date       nav  daily_return
5750     100016 2022-01-03  520.4608      0.000000
5751     100016 2022-01-04  515.0971     -0.010306
5752     100016 2022-01-05  521.7239      0.012865
5753     100016 2022-01-06  515.7880     -0.011377
5754     100016 2022-01-07  515.1639     -0.001210
...         ...        ...       ...           ...
6895     100016 2026-05-25  599.9335     -0.004227
6896     100016 2026-05-26  596.4426     -0.005819
6897     100016 2026-05-27  590.8555     -0.009367
6898     100016 2026-05-28  590.9452      0.000152
6899     100016 2026-05-29  583.6113     -0.012410

[1150 rows x 4 columns]

In [41]:
from pathlib import Path
project_root = Path.cwd()
if not (project_root / 'data').exists():
    project_root = project_root.parent
file_path_new = str(project_root / 'data' / 'processed') + '/'

In [42]:
df_1.to_csv(file_path_new + "01_fund_master.csv", index=False)
df_2.to_csv(file_path_new + "02_nav_history.csv", index=False)
df_3.to_csv(file_path_new + "03_aum_by_fund_house.csv", index=False)
df_4.to_csv(file_path_new + "04_monthly_sip_inflows.csv", index=False)
df_5.to_csv(file_path_new + "05_category_inflows.csv", index=False)
df_6.to_csv(file_path_new + "06_industry_folio_count.csv", index=False)
df_7.to_csv(file_path_new + "07_scheme_performance.csv", index=False)
df_8.to_csv(file_path_new + "08_investor_transactions.csv", index=False)
df_9.to_csv(file_path_new + "09_portfolio_holdings.csv", index=False)
df_10.to_csv(file_path_new + "10_benchmark_indices.csv", index=False)